export const predefinedCategories = [
    'Food',
    'Transport',
    'Entertainment',
    'Bills',
    'Shopping',
    'Car Insurance',
    'Mobile Phone Bill',
    'Bank Fees',
    'Electricity',
    'House Rent',
    'Petrol',
    'Grocery',
    'Netflix',
    'Karate Classes',
    'Internet Bill',
    'Parking',
    'Healthcare',
    'Education',
    'Subscriptions',
    'Savings & Investments',
    'Loan Payments',
    'Gym Membership',
    'Charity & Donations',
    'Miscellaneous',
    'Water Bill',
    'Gas Bill',
    'Home Maintenance',
    'Vehicle Maintenance',
    'Property Tax',
    'Life Insurance',
    'Health Insurance',
    'Dental Care',
    'Childcare',
    'School Fees',
    'Tuition Fees',
    'Books & Stationery',
    'Streaming Services (Disney+, Prime Video, etc.)',
    'Music Subscriptions (Spotify, Apple Music, etc.)',
    'Cloud Storage (Google Drive, iCloud, etc.)',
    'Software Subscriptions (Adobe, Microsoft 365, etc.)',
    'Emergency Fund',
    'Vacation & Travel',
    'Public Transport (Bus, Train, Metro)',
    'Ride-Sharing (Uber, Lyft, etc.)',
    'Hobbies & Leisure',
    'Dining Out',
    'Fast Food',
    'Pet Expenses',
    'Clothing & Accessories',
    'Beauty & Personal Care',
    'Haircuts & Grooming',
    'Gifts & Celebrations',
    'Home Security Services',
    'Legal Fees',
    'Professional Development (Courses, Certifications)',
    'Investment Fees',
    'Side Business Expenses',
    'Fun & Recreation',
    'Alcohol & Bars',
    'Cigarettes & Vaping',
    'Concerts & Events',
    'Lottery & Gambling',
    // Income-related categories
    'Salary',
    'Freelance Income',
    'Business Income',
    'Investment Income (Dividends, Interest, etc.)',
    'Rental Income',
    'Royalties',
    'Side Hustle Income',
    'Bonuses & Incentives',
    'Commission',
    'Grants & Scholarships',
    'Gifts & Inheritances',
    'Government Benefits (Pensions, Unemployment, etc.)',
    'Tax Refunds',
    'Sale of Assets',
    'Crypto Earnings',
    'Other Income'
];
